CREATE TABLE "shadowchar-saas_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "shadowchar-saas_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "shadowchar-saas_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_campaign_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_campaign_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaignId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"role" varchar(50) DEFAULT 'player' NOT NULL,
	"joinedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_campaign" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_campaign_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"description" text,
	"gmId" varchar(255) NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL,
	"setting" text,
	"notes" text,
	"imageUrl" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_character" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_character_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"campaignId" integer,
	"name" varchar(100) NOT NULL,
	"ancestry" varchar(50) NOT NULL,
	"novicePath" varchar(50),
	"expertPath" varchar(50),
	"masterPath" varchar(50),
	"level" integer DEFAULT 0 NOT NULL,
	"strength" integer DEFAULT 10 NOT NULL,
	"agility" integer DEFAULT 10 NOT NULL,
	"intellect" integer DEFAULT 10 NOT NULL,
	"will" integer DEFAULT 10 NOT NULL,
	"health" integer DEFAULT 0 NOT NULL,
	"insanity" integer DEFAULT 0 NOT NULL,
	"corruption" integer DEFAULT 0 NOT NULL,
	"background" text,
	"notes" text,
	"talents" json DEFAULT '[]'::json,
	"spells" json DEFAULT '[]'::json,
	"equipment" json DEFAULT '[]'::json,
	"isPublic" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "shadowchar-saas_account" ADD CONSTRAINT "shadowchar-saas_account_userId_shadowchar-saas_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."shadowchar-saas_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_post" ADD CONSTRAINT "shadowchar-saas_post_createdById_shadowchar-saas_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."shadowchar-saas_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_session" ADD CONSTRAINT "shadowchar-saas_session_userId_shadowchar-saas_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."shadowchar-saas_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_campaign_member" ADD CONSTRAINT "shadowchar-saas_campaign_member_campaignId_shadowchar-saas_campaign_id_fk" FOREIGN KEY ("campaignId") REFERENCES "public"."shadowchar-saas_campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_campaign_member" ADD CONSTRAINT "shadowchar-saas_campaign_member_userId_shadowchar-saas_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."shadowchar-saas_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_campaign" ADD CONSTRAINT "shadowchar-saas_campaign_gmId_shadowchar-saas_user_id_fk" FOREIGN KEY ("gmId") REFERENCES "public"."shadowchar-saas_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_character" ADD CONSTRAINT "shadowchar-saas_character_userId_shadowchar-saas_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."shadowchar-saas_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_character" ADD CONSTRAINT "shadowchar-saas_character_campaignId_shadowchar-saas_campaign_id_fk" FOREIGN KEY ("campaignId") REFERENCES "public"."shadowchar-saas_campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "shadowchar-saas_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "shadowchar-saas_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "shadowchar-saas_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "shadowchar-saas_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "campaign_member_campaign_id_idx" ON "shadowchar-saas_campaign_member" USING btree ("campaignId");--> statement-breakpoint
CREATE INDEX "campaign_member_user_id_idx" ON "shadowchar-saas_campaign_member" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "campaign_gm_id_idx" ON "shadowchar-saas_campaign" USING btree ("gmId");--> statement-breakpoint
CREATE INDEX "campaign_name_idx" ON "shadowchar-saas_campaign" USING btree ("name");--> statement-breakpoint
CREATE INDEX "character_user_id_idx" ON "shadowchar-saas_character" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "character_campaign_id_idx" ON "shadowchar-saas_character" USING btree ("campaignId");--> statement-breakpoint
CREATE INDEX "character_name_idx" ON "shadowchar-saas_character" USING btree ("name");