CREATE TABLE "shadowchar-saas_campaign_note" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_campaign_note_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"campaignId" integer NOT NULL,
	"authorId" varchar(255) NOT NULL,
	"title" varchar(100) NOT NULL,
	"content" text NOT NULL,
	"isPrivate" boolean DEFAULT false NOT NULL,
	"category" varchar(50) DEFAULT 'general',
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_plan" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_plan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"description" text,
	"priceInCents" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"interval" varchar(20) NOT NULL,
	"features" json DEFAULT '[]'::json,
	"isActive" boolean DEFAULT true NOT NULL,
	"maxCharacters" integer DEFAULT 5,
	"maxCampaigns" integer DEFAULT 2,
	"stripePriceId" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_subscription" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_subscription_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"planId" integer NOT NULL,
	"status" varchar(20) NOT NULL,
	"currentPeriodStart" timestamp with time zone NOT NULL,
	"currentPeriodEnd" timestamp with time zone NOT NULL,
	"cancelAtPeriodEnd" boolean DEFAULT false NOT NULL,
	"canceledAt" timestamp with time zone,
	"stripeCustomerId" varchar(255),
	"stripeSubscriptionId" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "shadowchar-saas_subscription_stripeSubscriptionId_unique" UNIQUE("stripeSubscriptionId")
);
--> statement-breakpoint
ALTER TABLE "shadowchar-saas_campaign_note" ADD CONSTRAINT "shadowchar-saas_campaign_note_campaignId_shadowchar-saas_campaign_id_fk" FOREIGN KEY ("campaignId") REFERENCES "public"."shadowchar-saas_campaign"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_campaign_note" ADD CONSTRAINT "shadowchar-saas_campaign_note_authorId_shadowchar-saas_user_id_fk" FOREIGN KEY ("authorId") REFERENCES "public"."shadowchar-saas_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_subscription" ADD CONSTRAINT "shadowchar-saas_subscription_userId_shadowchar-saas_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."shadowchar-saas_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shadowchar-saas_subscription" ADD CONSTRAINT "shadowchar-saas_subscription_planId_shadowchar-saas_plan_id_fk" FOREIGN KEY ("planId") REFERENCES "public"."shadowchar-saas_plan"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "campaign_note_campaign_id_idx" ON "shadowchar-saas_campaign_note" USING btree ("campaignId");--> statement-breakpoint
CREATE INDEX "campaign_note_author_id_idx" ON "shadowchar-saas_campaign_note" USING btree ("authorId");--> statement-breakpoint
CREATE INDEX "plan_name_idx" ON "shadowchar-saas_plan" USING btree ("name");--> statement-breakpoint
CREATE INDEX "plan_stripe_price_id_idx" ON "shadowchar-saas_plan" USING btree ("stripePriceId");--> statement-breakpoint
CREATE INDEX "subscription_user_id_idx" ON "shadowchar-saas_subscription" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "subscription_plan_id_idx" ON "shadowchar-saas_subscription" USING btree ("planId");--> statement-breakpoint
CREATE INDEX "subscription_stripe_subscription_id_idx" ON "shadowchar-saas_subscription" USING btree ("stripeSubscriptionId");