CREATE TABLE "shadowchar-saas_ancestries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_ancestries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"pt_br" varchar(100),
	"short_description" varchar(100),
	"ability_modifiers" jsonb,
	"talents_start" jsonb,
	"age_height_weight_table" jsonb,
	"languages" jsonb,
	"starting_items" jsonb,
	"source" varchar(100),
	"source_page" varchar(100),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"type" varchar(100),
	"price" varchar(100),
	"weight" varchar(100),
	"properties" json,
	"damage" varchar(100),
	"armor_defense" varchar(100),
	"notes" varchar(100),
	"source" varchar(100),
	"source_page" varchar(100),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_paths" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_paths_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"pt_br" varchar(100),
	"tier" varchar(20) NOT NULL,
	"description" json,
	"prerequisites" varchar(255),
	"talents_by_level" json,
	"source" varchar(255),
	"source_page" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "shadowchar-saas_spells" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "shadowchar-saas_spells_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"tradition" varchar(100),
	"rank" integer DEFAULT 0 NOT NULL,
	"type" varchar(100),
	"source" varchar(100),
	"source_page" varchar(100),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "ancestry_name_idx" ON "shadowchar-saas_ancestries" USING btree ("name");--> statement-breakpoint
CREATE INDEX "item_name_idx" ON "shadowchar-saas_items" USING btree ("name");--> statement-breakpoint
CREATE INDEX "path_name_idx" ON "shadowchar-saas_paths" USING btree ("name");--> statement-breakpoint
CREATE INDEX "spell_name_idx" ON "shadowchar-saas_spells" USING btree ("name");